# Generated by Django 5.1.3 on 2025-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_creditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='sale_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
